In [1]:
import numpy as np

In [ ]:
l1 = 100
l2 = 100

theta_t1 = 0
c = np.cos(np.radians(theta_t1))
s = np.sin(np.radians(theta_t1))
T1 = np.array([
    [c,0,-s,0],
    [0,1,0,0],
    [s,0,c,0],
    [0,0,0,1]
])

theta_t2 = 0
c = np.cos(np.radians(-theta_t2))
s = np.sin(np.radians(-theta_t2))
T2 = np.array([
    [1,0,0,0],
    [0,c,-s,0],
    [0,s,c,0],
    [0,0,0,1]
])

theta_t3 = 45
c = np.cos(np.radians(theta_t3))
s = np.sin(np.radians(theta_t3))
T3 = np.array([
    [c,-s,0,0],
    [s,c,0,0],
    [0,0,1,-l1],
    [0,0,0,1]
])

theta_t4 = 90
c = np.cos(np.radians(theta_t4))
s = np.sin(np.radians(theta_t4))
T4 = np.array([
    [c,0,-s,0],
    [0,1,0,0],
    [s,0,c,0],
    [0,0,0,1]
])

T5 = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,-l2],
    [0,0,0,1]
])

T = T1 @ T2 @ T3 @ T4 @ T5
print(T)

[[ 4.32978028e-17 -7.07106781e-01 -7.07106781e-01  7.07106781e+01]
 [ 4.32978028e-17  7.07106781e-01 -7.07106781e-01  7.07106781e+01]
 [ 1.00000000e+00  0.00000000e+00  6.12323400e-17 -1.00000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
